#!/bin/bash
# $Id: compressorstatus
# $auth: Steve Torchinsky <satorchi@apc.in2p3.fr>
# $created: Fri 13 Nov 2020 17:10:57 CET
# $license: GPLv3 or later, see https://www.gnu.org/licenses/gpl-3.0.txt
#
#           This is free software: you are free to change and
#           redistribute it.  There is NO WARRANTY, to the extent
#           permitted by law.
#
# print the pulse tube compressor status
compressor_commander.py 1 status
compressor_commander.py 2 status

