#!/bin/bash
# $Id: compressor1on
# $auth: Steve Torchinsky <satorchi@apc.in2p3.fr>
# $created: Fri 13 Nov 2020 17:00:55 CET
# $license: GPLv3 or later, see https://www.gnu.org/licenses/gpl-3.0.txt
#
#           This is free software: you are free to change and
#           redistribute it.  There is NO WARRANTY, to the extent
#           permitted by law.
#
# switch on pulse tube 1 compressor

compressor_commander.py 1 on
