#!/bin/bash
# $Id: copy2cc
# $auth: Steve Torchinsky <satorchi@apc.in2p3.fr>
# $created: Thu 31 Mar 2022 17:22:51 CEST
# $license: GPLv3 or later, see https://www.gnu.org/licenses/gpl-3.0.txt
#
#           This is free software: you are free to change and
#           redistribute it.  There is NO WARRANTY, to the extent
#           permitted by law.
#
# copy data from QubicStudio to the qubic-central archive

QS_DIR=pi@cam2:/qs2 
ARCHIVE_DIR=/archive
rsync -avt $QS_DIR/Data/ $ARCHIVE_DIR

