#!/bin/bash
# $Id: goto_el
# $auth: Steve Torchinsky <satorchi@apc.in2p3.fr>
# $created: Thu 05 Jun 2025 19:29:16 CEST
# $license: GPLv3 or later, see https://www.gnu.org/licenses/gpl-3.0.txt
#
#           This is free software: you are free to change and
#           redistribute it.  There is NO WARRANTY, to the extent
#           permitted by law.
#
# go to the given elevation
goto_pos.py el $1


