#!/bin/bash
# $Id: show_hk
# $auth: Steve Torchinsky <satorchi@apc.in2p3.fr>
# $created: Thu 18 Nov 2021 17:39:45 CET
# $license: GPLv3 or later, see https://www.gnu.org/licenses/gpl-3.0.txt

#           This is free software: you are free to change and
#           redistribute it.  There is NO WARRANTY, to the extent
#           permitted by law.

# wrapper to watch the temperatures with update every second

watch -c -n1 show_hk.py
